### ISSUE TITLE
hey bro kann ich dein dc

### ISSUE THREAD

**Issue by pizzahendygamin** [notLe0nard/IR-Flip#2]
hey wollte erstmal danke sagen das is so nice aber 2. bin zu blöd sonen infrarot ding mit den leds zu bauen und habe aber so einen infrarot adapter der per usb c ans handy kommt is es möglich das umzu coden damit das auch damit funktioniert?

**Comment by notLe0nard** [comment]
Ne. Aber für den usbC adapter gibts auch apps. wenn du nen adapter basteln willst: https://youtu.be/cD2c2DhlvuQ?si=tMci5PM3t40K9Vzf

**Comment by pizzahendygamin** [comment]
ja ich weiß aber nd so eine apk wie du gemacht hast und diese usb c dinger haben größere reichweite und joa deine is halt die beste dafür oder kennst du irgendsone app die das gleiche kann
